tars:
  - url: http://download.savannah.gnu.org/releases/acl/acl-2.2.53.tar.gz
    md5: 007aabf1dbb550bcddde52a244cd1070
  - url: http://download.savannah.gnu.org/releases/attr/attr-2.4.48.tar.gz
    md5: bc1e5cb5c96d99b24886f1f527d3bb3d
  - url: http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.xz
    md5: 50f97f4159805e374639a73e2636f22e
  - url: http://ftp.gnu.org/gnu/automake/automake-1.16.1.tar.xz
    md5: 53f38e7591fa57c3d2cee682be668e5b
  - url: http://ftp.gnu.org/gnu/bash/bash-4.4.18.tar.gz
    md5: 518e2c187cc11a17040f0915dddce54e
  - url: http://ftp.gnu.org/gnu/bc/bc-1.07.1.tar.gz
    md5: cda93857418655ea43590736fc3ca9fc
  - url: http://ftp.gnu.org/gnu/binutils/binutils-2.31.1.tar.xz
    md5: 5b7c9d4ce96f507d95c1b9a255e52418
  - url: http://ftp.gnu.org/gnu/bison/bison-3.0.5.tar.xz
    md5: 3e54f20988ecd1b62044e25481e5f06b
  - url: http://anduin.linuxfromscratch.org/LFS/bzip2-1.0.6.tar.gz
    md5: 00b516f4704d4a7cb50a1d97e6e8e15b
  - url: https://github.com/libcheck/check/releases/download/0.12.0/check-0.12.0.tar.gz
    md5: 31b17c6075820a434119592941186f70
  - url: http://ftp.gnu.org/gnu/coreutils/coreutils-8.30.tar.xz
    md5: ab06d68949758971fe744db66b572816
  - url: https://dbus.freedesktop.org/releases/dbus/dbus-1.12.10.tar.gz
    md5: c3e12b4206e2a7da39d7cc42567790ef
  - url: http://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.1.tar.gz
    md5: 2ac8405a4c7ca8611d004fe852966c6f
  - url: http://ftp.gnu.org/gnu/diffutils/diffutils-3.6.tar.xz
    md5: 07cf286672ced26fba54cd0313bdc071
  - url: https://dev.gentoo.org/~blueness/eudev/eudev-3.2.5.tar.gz
    md5: 6ca08c0e14380f87df8e8aceac123671
  - url: https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.44.3/e2fsprogs-1.44.3.tar.gz
    md5: 6bd765f3cf8f15740cdf81e71e88f2a4
  - url: https://sourceware.org/ftp/elfutils/0.173/elfutils-0.173.tar.bz2
    md5: 35decb1ebfb90d565e4c411bee4185cc
  - url: https://prdownloads.sourceforge.net/expat/expat-2.2.6.tar.bz2
    md5: ca047ae951b40020ac831c28859161b2
  - url: https://prdownloads.sourceforge.net/expect/expect5.45.4.tar.gz
    md5: 00fce8de158422f5ccd2666512329bd2
  - url: ftp://ftp.astron.com/pub/file/file-5.34.tar.gz
    md5: 44b0b6983462b18f96403d4d3ad80254
  - url: http://ftp.gnu.org/gnu/findutils/findutils-4.6.0.tar.gz
    md5: 9936aa8009438ce185bea2694a997fc1
  - url: https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
    md5: 2882e3179748cc9f9c23ec593d6adc8d
  - url: http://ftp.gnu.org/gnu/gawk/gawk-4.2.1.tar.xz
    md5: 95cf553f50ec9f386b5dfcd67f30180a
  - url: http://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.xz
    md5: 4ab282f414676496483b3e1793d07862
  - url: http://ftp.gnu.org/gnu/gdbm/gdbm-1.17.tar.gz
    md5: f20ce117abc6f302ecf62c34d41c1ecf
  - url: http://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz
    md5: df3f5690eaa30fd228537b00cb7b7590
  - url: http://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.xz
    md5: c81d2388896379997bc359d4f2084239
  - url: http://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz
    md5: f58fa8001d60c4c77595fbbb62b63c1d
  - url: http://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz
    md5: 9e251c0a618ad0824b51117d5d9db87e
  - url: http://ftp.gnu.org/gnu/grep/grep-3.1.tar.xz
    md5: feca7b3e7c7f4aab2b42ecbfc513b070
  - url: http://ftp.gnu.org/gnu/groff/groff-1.22.3.tar.gz
    md5: cc825fa64bc7306a885f2fb2268d3ec5
  - url: https://ftp.gnu.org/gnu/grub/grub-2.02.tar.xz
    md5: 8a4a2a95aac551fb0fba860ceabfa1d3
  - url: http://ftp.gnu.org/gnu/gzip/gzip-1.9.tar.xz
    md5: 9492c6ccb2239ff679a5475a7bb543ed
  - url: http://anduin.linuxfromscratch.org/LFS/iana-etc-2.30.tar.bz2
    md5: 3ba3afb1d1b261383d247f46cb135ee8
  - url: http://ftp.gnu.org/gnu/inetutils/inetutils-1.9.4.tar.xz
    md5: 87fef1fa3f603aef11c41dcc097af75e
  - url: https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz
    md5: 12e517cac2b57a0121cda351570f1e63
  - url: https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-4.18.0.tar.xz
    md5: 8b8680e91390c57cab788fbf8e929479
  - url: https://www.kernel.org/pub/linux/utils/kbd/kbd-2.0.4.tar.xz
    md5: c1635a5a83b63aca7f97a3eab39ebaa6
  - url: https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-25.tar.xz
    md5: 34f325cab568f842fdde4f8b2182f220
  - url: http://www.greenwoodsoftware.com/less/less-530.tar.gz
    md5: 6a39bccf420c946b0fd7ffc64961315b
  - url: http://www.linuxfromscratch.org/lfs/downloads/8.3/lfs-bootscripts-20180820.tar.bz2
    md5: 57c9501afe65b95bc4428f344ab2c85e
  - url: https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.25.tar.xz
    md5: 6666b839e5d46c2ad33fc8aa2ceb5f77
  - url: ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
    md5: 83b89587607e3eb65c70d361f13bab43
  - url: http://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.0.tar.gz
    md5: b7437a5020190cfa84f09c412db38902
  - url: http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.xz
    md5: 1bfb9b923f2c1339b4d2ce1807064aa5
  - url: https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.18.5.tar.xz
    md5: 22851fe6c82db6673a844bbb7c62df67
  - url: http://ftp.gnu.org/gnu/m4/m4-1.4.18.tar.xz
    md5: 730bb15d96fffe47e148d1e09235af82
  - url: http://ftp.gnu.org/gnu/make/make-4.2.1.tar.bz2
    md5: 15b012617e7c44c0ed482721629577ac
  - url: http://download.savannah.gnu.org/releases/man-db/man-db-2.8.4.tar.xz
    md5: ab41db551f500e4a595b11203b86c67a
  - url: https://mirrors.edge.kernel.org/pub/linux/docs/man-pages/Archive/man-pages-4.16.tar.xz
    md5: ad9f1ff81276fe8d90d077484d6d4b5e
  - url: https://github.com/mesonbuild/meson/releases/download/0.47.1/meson-0.47.1.tar.gz
    md5: 5ed95fd4e9c7634f7cf3482d352804e7
  - url: https://ftp.gnu.org/gnu/mpc/mpc-1.1.0.tar.gz
    md5: 4125404e41e482ec68282a2e687f6c73
  - url: http://www.mpfr.org/mpfr-4.0.1/mpfr-4.0.1.tar.xz
    md5: b8dd19bd9bb1ec8831a6a582a7308073
  - url: https://github.com/ninja-build/ninja/archive/v1.8.2/ninja-1.8.2.tar.gz
    md5: 5fdb04461cc7f5d02536b3bfc0300166
  - url: http://ftp.gnu.org/gnu/ncurses/ncurses-6.1.tar.gz
    md5: 98c889aaf8d23910d2b92d65be2e737a
  - url: https://openssl.org/source/openssl-1.1.0i.tar.gz
    md5: 9495126aafd2659d357ea66a969c3fe1
  - url: http://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz
    md5: 78ad9937e4caadcba1526ef1853730d5
  - url: https://www.cpan.org/src/5.0/perl-5.28.0.tar.xz
    md5: f3245183c0a08f65e94a3333995af08e
  - url: https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
    md5: f6e931e319531b736fadc017f470e68a
  - url: https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-3.3.15.tar.xz
    md5: 2b0717a7cb474b3d6dfdeedfbad2eccc
  - url: https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.1.tar.xz
    md5: bbba1f701c02fb50d59540d1ff90d8d1
  - url: https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz
    md5: eb8c2a6b1447d50813c02714af4681f3
  - url: https://docs.python.org/ftp/python/doc/3.7.0/python-3.7.0-docs-html.tar.bz2
    md5: c4637cf2a9a6ebb8c5e9dc8ff13fb4cb
  - url: http://ftp.gnu.org/gnu/readline/readline-7.0.tar.gz
    md5: 205b03a87fc83dab653b628c59b9fc91
  - url: http://ftp.gnu.org/gnu/sed/sed-4.5.tar.xz
    md5: ade8f8c2c548bf41f74db2dcfc37e4e3
  - url: https://github.com/shadow-maint/shadow/releases/download/4.6/shadow-4.6.tar.xz
    md5: b491fecbf1232632c32ff8f1437fd60e
  - url: http://www.infodrom.org/projects/sysklogd/download/sysklogd-1.5.1.tar.gz
    md5: c70599ab0d037fde724f7210c2c8d7f8
  - url: https://github.com/systemd/systemd/archive/v239/systemd-239.tar.gz
    md5: 6137e3f50390391cf34521d071a1a078
  - url: http://anduin.linuxfromscratch.org/LFS/systemd-man-pages-239.tar.xz
    md5: b3be99a8fff33c773f034151b16eb1b8
  - url: http://download.savannah.gnu.org/releases/sysvinit/sysvinit-2.90.tar.xz
    md5: 7b6a16bde3da494b6aac7283b79c81de
  - url: http://ftp.gnu.org/gnu/tar/tar-1.30.tar.xz
    md5: 2d01c6cd1387be98f57a0ec4e6e35826
  - url: https://downloads.sourceforge.net/tcl/tcl8.6.8-src.tar.gz
    md5: 81656d3367af032e0ae6157eff134f89
  - url: http://ftp.gnu.org/gnu/texinfo/texinfo-6.5.tar.xz
    md5: 3715197e62e0e07f85860b3d7aab55ed
  - url: https://www.iana.org/time-zones/repository/releases/tzdata2018e.tar.gz
    md5: 97d654f4d7253173b3eeb76a836dd65e
  - url: http://anduin.linuxfromscratch.org/LFS/udev-lfs-20171102.tar.bz2
    md5: d92afb0c6e8e616792068ee4737b0d24
  - url: https://www.kernel.org/pub/linux/utils/util-linux/v2.32/util-linux-2.32.1.tar.xz
    md5: 9e5b1b8c1dc99455bdb6b462cf9436d9
  - url: ftp://ftp.vim.org/pub/vim/unix/vim-8.1.tar.bz2
    md5: 1739a1df312305155285f0cfa6118294
  - url: https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.44.tar.gz
    md5: af4813fe3952362451201ced6fbce379
  - url: https://tukaani.org/xz/xz-5.2.4.tar.xz
    md5: 003e4d0b1b1899fc6e3000b24feddf7c
  - url: https://zlib.net/zlib-1.2.11.tar.xz
    md5: 85adef240c5f370b308da8c938951a68

patches:
  - url: http://www.linuxfromscratch.org/patches/lfs/8.3/bzip2-1.0.6-install_docs-1.patch
    md5: 6a5ac7e89b791aae556de0f745916f7f
  - url: http://www.linuxfromscratch.org/patches/lfs/8.3/coreutils-8.30-i18n-1.patch
    md5: a9404fb575dfd5514f3c8f4120f9ca7d
  - url: http://www.linuxfromscratch.org/patches/lfs/8.3/glibc-2.28-fhs-1.patch
    md5: 9a5997c3452909b1769918c759eff8a2
  - url: http://www.linuxfromscratch.org/patches/lfs/8.3/kbd-2.0.4-backspace-1.patch
    md5: f75cca16a38da6caa7d52151f7136895
  - url: http://www.linuxfromscratch.org/patches/lfs/8.3/ninja-1.8.2-add_NINJAJOBS_var-1.patch
    md5: f537a633532492e805aa342fa869ca45
  - url: http://www.linuxfromscratch.org/patches/lfs/8.3/sysvinit-2.90-consolidated-1.patch
    md5: b7872b43a97a81bac4f9fc8ffaef4364
  - url: http://www.linuxfromscratch.org/patches/lfs/8.3/systemd-239-glibc_statx_fix-1.patch
    md5: a44057d6a6ca69760bafc126458d89e5
